version: "3.8"
services:
  mqtt_broker:
    container_name: mqtt_broker
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosq_data_volume:/mosquitto/data
      - mosq_logs_volume:/mosquitto/log
    networks:
      - iot_cloud
  
networks: 
  iot_cloud:

volumes:
  mosq_data_volume:
  mosq_logs_volume: