version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1881:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-logs:/mosquitto/log
      - mosquitto-data:/mosquitto/data
      - ./passwordfile:/mosquitto/passwordfile

volumes:
    mosquitto-logs:
    mosquitto-data:
